global:
  scrape_interval:     15s
  external_labels:
    env: 'infrastructure'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s

rule_files:
  - "/alertmanager/alert.rules/alerts.rules.yml"

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 5s

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://linux.org
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*)(:80)?'
        target_label: __param_target
      - source_labels: [__address__]
        regex: '(.*)'
        replacement: '${1}'
        target_label: instance
      - source_labels: []
        regex: '.*'
        target_label: __address__
        replacement: blackbox:9115