groups:

- name: Alertes monitoring
  rules:
    - alert: OutOfMemory
      expr: (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes * 100 < 10
      for: 15m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Out of memory (instance {{ $labels.instance }})"
        description: "Out of memory (lesst than 10% remaining)    VALUE = {{ $value }}    LABELS: {{ $labels.job }} : {{ $labels.instance }}"

    - alert: UnusualNetworkThroughputIn
      expr: sum by (instance) (irate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 100
      for: 15m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Unusual network throughput in (instance {{ $labels.instance }})"
        description: "Unusual network throughput in (> 100 MB/s)    VALUE = {{ $value }}    LABELS: {{ $labels.job }} : {{ $labels.instance }}"

    - alert: UnusualNetworkThroughputOut
      expr: sum by (instance) (irate(node_network_transmit_bytes_total[2m])) / 1024 / 1024 > 100
      for: 15m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Unusual network throughput out (instance {{ $labels.instance }})"
        description: "Unusual network throughput out (> 100 MB/s)    VALUE = {{ $value }}    LABELS: {{ $labels.job }} : {{ $labels.instance }}"

    - alert: UnusualDiskReadRate
      expr: sum by (instance) (irate(node_disk_read_bytes_total[2m])) / 1024 / 1024 > 50
      for: 15m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Unusual disk read rate (instance {{ $labels.instance }})"
        description: "Unusual disk read rate (> 50 MB/s)    VALUE = {{ $value }}    LABELS: {{ $labels.job }} : {{ $labels.instance }}"

    - alert: UnusualDiskWriteRate
      expr: sum by (instance) (irate(node_disk_written_bytes_total[2m])) / 1024 / 1024 > 50
      for: 15m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Unusual disk write rate (instance {{ $labels.instance }})"
        description: "Unusual disk write rate (> 50 MB/s)    VALUE = {{ $value }}    LABELS: {{ $labels.job }} : {{ $labels.instance }}"

    - alert: OutOfDiskSpace
      expr: min(node_filesystem_free_bytes{mountpoint=~".*"}) / min(node_filesystem_size_bytes{mountpoint=~".*"}) * 100 < 20
      for: 10m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Out of disk space (instance {{ $labels.instance }})"
        description: "Out of disk space (lesst than 20% remaining)    VALUE = {{ $value }}    LABELS: {{ $labels.job }} : {{ $labels.instance }}"

    - alert: CpuLoad
      expr: node_load5 / (count without (cpu, mode) (node_cpu_seconds_total{mode="system"})) > 0.5
      for: 5m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "CPU load (instance {{ $labels.instance }})"
        description: "CPU (5m) load    VALUE = {{ $value }}    LABELS: {{ $labels.job }} : {{ $labels.instance }}"

    - alert: Health endpoint down
      expr: probe_success == 0
      for: 10s
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Health endpoint is down"
        description: "Health endpoint is down : {{ $labels.addresse }}"

    - alert: Certificate expire
      expr: probe_ssl_earliest_cert_expiry{job="blackbox"} - time() < 86400 * 30
      for: 10m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "SSL certificate expire"
        description: "SSL certificate expires in 3 months {{ $labels.addresse }}"
